apiVersion: v1
kind: ConfigMap
metadata:
  name: routr-bootstrap
data:
  bootstrap.yml: |-
    - apiVersion: v1draft1
      kind: Domain
      metadata:
        name: Local Domain
      spec:
        context:
          domainUri: sip.local
    - apiVersion: v1draft1
      kind: Agent
      metadata:
        name: John Doe
      spec:
        domains: ['sip.local']
        credentials:
          username: '1001'
          secret: '1234'
    - apiVersion: v1draft1
      kind: Agent
      metadata:
        name: Jane Doe
      spec:
        domains: ['sip.local']
        credentials:
          username: '1002'
          secret: '1234'
    - apiVersion: v1draft1
      kind: Peer
      metadata:
        name: Asterisk PBX
      spec:
        device: 'sip.local'
        credentials:
          username: ast
          secret: 'changeit'
