apiVersion: v1
kind: ConfigMap
metadata:
  name: routr-config
data:
  config.yml: |-
    apiVersion: v1draft1
    spec:
      recordRoute: true
      registrarIntf: Internal
      useToAsAOR: true
      transport:
        - protocol: udp
          port: 5060
        - protocol: tcp
          port: 5060
      logging:
        traceLevel: 0
