apiVersion: v1
kind: ConfigMap
metadata:
  name: routr-entrypoint
data:
  entrypoint.sh: |-
    ./opt/routr/run.sh &
    while ! nc -z localhost 4567; do sleep 0.1; done
    ./opt/routr/rctl create -f /opt/routr/bootstrap.yml
    while sleep 3600; do :; done
