apiVersion: v1
kind: Service
metadata:
  name: routr
  labels:
    app: routr
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local # This will cause the load balancer to send the client ip
  ports:
  - name: sip
    port: 5060
  - name: https
    port: 443
    targetPort: 4567
  selector:
    app: routr
    tier: signaling
